apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: basic-demo
  namespace: basic-demo
  labels:
    backstage.io/kubernetes-id: sandbox-demo
spec:
  scaleTargetRef:
    name: sandbox-demo
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-operated.fw-prometheus:9090
      metricName: nginx_ingress_controller_requests
      threshold: '5'
      activationThreshold: '.001'
      query: sum(rate(nginx_ingress_controller_requests{host="demo.sandbox.hillghost.com"}[5m]))
  - type: cron
    metadata:
      # Required
      timezone: America/Denver  # The acceptable values would be a value from the IANA Time Zone Database.
      start: 40 * * * *       # Every hour on the 30th minute
      end: 50 * * * *         # Every hour on the 45th minute
      desiredReplicas: "1"
