apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sandbox-demo
  description: A great cool demo
  annotations:
    circleci.com/project-slug: github/FairwindsOps/docker-demo
    backstage.io/kubernetes-id: sandbox-demo
    backstage.io/kubernetes-namespace: basic-demo
    argocd/app-name: sandbox-demo
  links:
    - url: https://demo.sandbox.hillghost.com
      title: Web UI
spec:
  type: service
  lifecycle: production
  owner: research
  system: public-websites
